### ISSUE TITLE
Closed-source?

### ISSUE THREAD

**Issue by AaronBeaudoin** [odoo-ide/vscode-odoo#28]
Are there any plans to open-source this plugin? I'd be interested in contributing, but it looks like this repo is just for issues.

**Comment by trinhanhngoc** [comment]
Yes. I think I will open-source this project at some point in the future. Currently, I am working full time on some Odoo IDE projects (PyCharm, VSCode,...), so I need a way to keep dedicating my time to these very time-consuming projects.

**Comment by trinhanhngoc** [comment]
For the VSCode extension, I plan to create a freemium model. It's a way to motivate me as well as a way for people to support the extension development.
