### ISSUE TITLE
I use Pyright for other projects—do I have to enable and disable it every time?

### ISSUE THREAD

**Issue by AaronBeaudoin** [odoo-ide/vscode-odoo#29]
You suggest in the README to disable the regular Pyright extension when working with Odoo projects. However, sometimes I work with other Python projects that do not involve Odoo, so I need Pyright for those projects. Is there a way for me to avoid having to enable and disable the Pyright extension each time when switching between projects?

EDIT: I don't typically use a workspace—I just open my project directory in a new window in VS Code and rely on whatever is in the `.vscode/` directory.

**Comment by trinhanhngoc** [comment]
Currently, VSCode doesn't provide any methods to programmatically enable or disable an extension. So I cannot make any improvements here.
