### ISSUE TITLE
custom addons not detected in vscode (its just warning)

### ISSUE THREAD

**Issue by Burnaviour** [odoo-ide/vscode-odoo#31]
custom addons are not detected in vs code using odoo extension its auto-suggesting odoo addons but not suggest custom addons models.I have attached pyright warning. 
![image](https://github.com/odoo-ide/vscode-odoo/assets/58103972/12dbec8c-0196-49d0-9bdd-093f2a048969)

**Comment by trinhanhngoc** [comment]
Hello @Burnaviour , I need more information to be able to support:

1. Your VSCode version + Odoo extension version
2. Your VSCode workspace structure

**Comment by Burnaviour** [comment]
thank you for your response here are the details my odoo extension **version is v0.6.4** and vs code **version 1.81**
![image](https://github.com/odoo-ide/vscode-odoo/assets/58103972/f93d242d-a766-492d-a2f4-02b423e0e85e)

**Comment by trinhanhngoc** [comment]
@Burnaviour , You can follow these steps:

1.  Check if the module that defines the `all.users` model is in the dependencies of the module containing the warning (directly or indirectly through `depends` in manifest).
2. I assume that the `custom_addons` folder is a valid addons path. You need to add the `custom_addons` folder to the extra paths setting as documented at https://microsoft.github.io/pyright/#/import-resolution.

**Comment by Burnaviour** [comment]
as per my module all.users is defined and working its just the pyright which is thwing waring and the odoo extension which is unable to detect all my custom modules models. In addition before posting the issue i tried this 2nd step you mentioned there are a lot of options option the told I have defined stub path in my workspace here is my setting.json  `"python.analysis.stubPath": "/opt/odoo16/custom_addons",`

**Comment by Burnaviour** [comment]
Thank you for your help i have fixed the issue
