### ISSUE TITLE
No code completion for `http.request.redirect`?

### ISSUE THREAD

**Issue by AaronBeaudoin** [odoo-ide/vscode-odoo#32]
It looks like in Odoo 16.0 the `http.local_redirect` function no longer exists and there is now a `http.request.redirect` function. But the new function doesn't show up in code completion. What version of Odoo is code completion targeting, and can I change it?

**Comment by trinhanhngoc** [comment]
Hi @AaronBeaudoin , The Odoo extension automatically determines Odoo version to provide appropriate completion. I just checked again, and everything is working fine for me.

<img width="1624" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/9052a9c0-8d8d-473e-9427-87f18a3892f0">

**Comment by AaronBeaudoin** [comment]
How does it determine the Odoo version? I am using the Odoo 16.0 source code just like in your screenshot yet the redirect function is not detected:
![image](https://github.com/odoo-ide/vscode-odoo/assets/26592486/019312f9-2194-419c-863a-5dc4b71a7a9d)

**Comment by AaronBeaudoin** [comment]
Nevermind! I previously had the Odoo 13.0 source code and I replaced with the Odoo 16.0 source code, and it looks like I just needed to reload VS Code in order for the extension to re-initialize and pick up the new source code.
