### ISSUE TITLE
Not working with custom project structure

### ISSUE THREAD

**Issue by acgonzales** [odoo-ide/vscode-odoo#33]
Can't seem to make it work using this project structure:

```
project/
├─ addons/
│  ├─ enterprise/    ->    odoo enterprise
│  ├─ other_addons_repository/    ->    custom addons repository
│  │  ├─ addons_1/    ->    sample custom addon
│  │  │  ├─ __manifest__.py
├─ src/
│  ├─ odoo/    -> odoo base code
```

Current behavior is its like there is no language server installed at all. No code-completion, type-hinting, like coding in notepad.

I had already set `python.languageServer` to `None` as suggested in the docs.

Odoo server is running in a Docker container.

Any suggestions as to how I can make this work?

**Comment by trinhanhngoc** [comment]
Hello @acgonzales, What version of VSCode + Odoo extension are you using?

Anyway, when using the Odoo extension, you don't need to manually set `python.languageServer` to `None` since the Odoo extension will set it automatically if the project is an Odoo project.

**Comment by acgonzales** [comment]
VS Code: 1.82.2
Odoo: v0.8.0

Was able to make it work initially by creating `pyrightconfig.json` and adding `extraPaths`. idk what happened its not working again

**Comment by rgarofalo** [comment]
this should be noted in the readme. For some absurd reason if you have a .gitignore in the root, the excluded paths present in .gitignore are not taken into account by vscode for the workspaceContains event. Consequently if you have a complex structure this extension does not activate

**Comment by trinhanhngoc** [comment]
Hello @rgarofalo , 

Thanks for the information!
