### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by hojati** [odoo-ide/vscode-odoo#34]
Hi,
when i install the extention remotely in vscode it doesnt work. Below is the output:

`/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/user/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.8.2-linux-x64/lib/binding/node-v108-linux-x64/better_sqlite3.node)`

i use ubuntu 16.04 remotely for odoo 10

**Comment by trinhanhngoc** [comment]
Hi @hojati . This is a known error (https://github.com/WiseLibs/better-sqlite3/issues/990) on older Ubuntu. I will consider adding the support for older Ubuntu in the next version.

**Comment by trinhanhngoc** [comment]
Hi @hojati , The new version 0.9.0 has been released with support for Ubuntu 16.0 in remote development.
