### ISSUE TITLE
Pyright config file not picking up

### ISSUE THREAD

**Issue by arryph** [odoo-ide/vscode-odoo#54]
pyrightconfig.json file is not being read by vscode, what should be done to be able to config pyright using config file?

**Comment by trinhanhngoc** [comment]
Hello @arryph ,

How do you structure your workspace? According to the [pyright documentation](https://microsoft.github.io/pyright/#/configuration?id=sample-config-file), `pyrightconfig.json` should be placed at the workspace root.
