### ISSUE TITLE
Unresolved References Issue in Odoo with VSCode

### ISSUE THREAD

**Issue by hafizhlf** [odoo-ide/vscode-odoo#63]
**Problem:**
I have encountered a persistent issue of unresolved references in my Odoo project when using Visual Studio Code (VSCode). This problem specifically arises when inspecting the Odoo core addons.

**Steps to Reproduce:**
1. Open the Odoo project in VSCode.
2. Navigate to the Odoo core addons specifically `project` addons.
3. Observe unresolved references in the code.

**Expected Behavior:**
I expect that all references in the Odoo core addons should be resolved without any issues, enabling smooth navigation and development within the project.

**Actual Behavior:**
The VSCode environment is showing unresolved references, which hampers the development process and makes it challenging to navigate through the codebase effectively.

Additional Information:
- Odoo Version: 17.0
- VSCode Version: 1.84.2
- Operating System: Windows 11 (SSH to Ubuntu 22.04 VM)
- Odoo IDE Version: v0.15.0

**Screenshots:**
![image](https://github.com/odoo-ide/vscode-odoo/assets/15645495/08055d10-0678-4b2a-8554-972235645879)

**Comment by trinhanhngoc** [comment]
Hello @hafizhlf ,

I could not reproduce this problem. Everything is working as expected for me.

<img width="1624" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/6e546fb6-35d3-49fe-b35b-47ce19006c73">

**Comment by hafizhlf** [comment]
I am closing the current issue for now. I have decided to take some time to investigate the problem further on my own.

I appreciate the assistance and support provided thus far. If I come across any new information or have additional questions, I will not hesitate to reopen the issue and reach out for help.
