### ISSUE TITLE
Unresolved field references inside xpath

### ISSUE THREAD

**Issue by hafizhlf** [odoo-ide/vscode-odoo#65]
**Problem:**
The issue involves unresolved references in an inheritance view where the field 'unit_cost' within 'line_ids' is not being referenced correctly

**Code Snippet:**
```
<xpath expr="//field[@name='line_ids']/tree/field[@name='estimated_cost']" position="before">
    <field name="unit_cost" widget="monetary"/>
</xpath>
```

**Screenshots:**
![image](https://github.com/odoo-ide/vscode-odoo/assets/15645495/ef6372ed-6403-4f15-936f-75186ae93ce8)

**Comment by trinhanhngoc** [comment]
Hello @hafizhlf ,

This is a known issue because the extension currently does not have proper support for view inheritance yet (#55).

**Comment by trinhanhngoc** [comment]
Hello @hafizhlf ,

This issue will be addessed in the next version. Read more: https://odoo-ide.com/blog/news-1/vscode-odoo-0-19-30.
