### ISSUE TITLE
Auto Imports to Resolve Missing Object

### ISSUE THREAD

**Issue by gustitammam** [odoo-ide/vscode-odoo#66]
Hi @trinhanhngoc,

Since the Pylance is disabled, what's the alternative for this feature?
https://code.visualstudio.com/docs/python/editing#_enable-auto-imports

In PyCharm it works to fix warnings like this:
![image](https://github.com/odoo-ide/vscode-odoo/assets/11481845/b21e37f5-849d-43b8-aa0b-1c58e49a2188)

Is it possible to do so in VsCode?

**Comment by trinhanhngoc** [comment]
Hello @gustitammam ,

I have already planned to implement this feature in the Odoo IDE plugin (#21).

**Comment by gustitammam** [comment]
Okay, I will close this issue as it appears to be a duplicate. Thank you.
