### ISSUE TITLE
VS Code cannot find models in XML file (e.g. Could not find model 'ir.ui.view')

### ISSUE THREAD

**Issue by cimbaIG** [odoo-ide/vscode-odoo#67]
Hi Trinh! First of all I must say I really appreciate your commitment to this project.

Everything works fine for me except XML files. There models cannot be found. For instance VS Code throws problem which states: Could not find model 'ir.ui.view'. Why is this happening?

Best regards!

**Comment by trinhanhngoc** [comment]
`ir.ui.view` is a built-in model defined in the Odoo source code. Please make sure that you have also added the Odoo source source code to your VSCode workspace.

**Comment by mhrafin** [comment]
Hey i seem to can't figure out the path, i inserted this `/home/raf/odoodevelopment/17.0/odoo/addons/base/`
Yet it seems vscode is not detecting it. I also tried `/home/raf/odoodevelopment/17.0/`
Heres what my directory looks like,

![Image](https://github.com/user-attachments/assets/4f07d783-d50b-42de-8a62-2ecab3d772cd)

I tried all these paths,

![Image](https://github.com/user-attachments/assets/a6dce3c8-9cc8-4f72-b9c3-8c1f41c82d65)
