### ISSUE TITLE
JS support?

### ISSUE THREAD

**Issue by Isaachintosh** [odoo-ide/vscode-odoo#68]
Is there any way to get the same  inheritance visualization for debug or write javascript code using this IDE, with code suggestions, as the same way that occurs today with the python part?

**Comment by trinhanhngoc** [comment]
Hello @Isaachintosh ,

You can generate `jsconfig.json` (or `tsconfig.json`) to activate the built-in JS support. However, many things in the Odoo JS framework do not follow standard JS and are thus not supported. In the future, I will add JS support to the Odoo IDE extension to make VSCode better understand the Odoo JS framework.

Refs:

- https://www.odoo.com/documentation/master/developer/reference/cli.html#tsconfig-generator
- https://github.com/odoo/odoo/tree/master/addons/web/tooling
