### ISSUE TITLE
Filter indexed files

### ISSUE THREAD

**Issue by abd-msyukyu-odoo** [odoo-ide/vscode-odoo#69]
Is there a way to prevent indexing some files (like `.po` files used for translations)? There are a lot of them in the Odoo project and it eats cpu performance at launch.

Many thanks for the great extension!

**Comment by trinhanhngoc** [comment]
Hello @abd-msyukyu-odoo ,

The Odoo IDE extension has already been optimised for indexing performance. Only new or changed files are indexed at launch.
