### ISSUE TITLE
Support VSCode 1.88

### ISSUE THREAD

**Issue by milouk** [odoo-ide/vscode-odoo#70]
Hello,

Thanks for your extension. I have been using it without any issues but since some time i get the following message:

Im using:

Version: 1.88.0-insider
Commit: 7107b38665e428a974c06b2c6e8f67a9a078aefd
Date: 2024-03-13T06:02:12.129Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.2.0

<img width="391" alt="Screenshot 2024-03-13 at 15 58 29" src="https://github.com/odoo-ide/vscode-odoo/assets/22796276/251a857a-b67a-46de-8688-f26b5709efee">

**Comment by trinhanhngoc** [comment]
Hello @milouk ,

I will add support for VSCode 1.88.0 in the next version released this week.

**Comment by trinhanhngoc** [comment]
Hello @milouk ,

The new version 0.22.3 has been released with support for VSCode 1.88.
