### ISSUE TITLE
[Odoo 16] Base module does not import correctly

### ISSUE THREAD

**Issue by agustin-eticco** [odoo-ide/vscode-odoo#71]
The rest of the Odoo addons are importing correctly, but the fields and functions of the base module, e.g. res.partner, are not importing correctly.

I only get my custom fields or functions loaded into res.partner. I have imported in my workspace the complete Odoo 16 project and I don't see any loading errors in the extension log. I have tried reinstalling Python and the extension and that doesn't work either. Any idea what's going on?

By the way, the Python module needed for the extension installs Pylance, and with this extension enabled it does not warn me correctly about errors.

Thanks for your work, it's helping me a lot with my Odoo development!

![image](https://github.com/odoo-ide/vscode-odoo/assets/83392263/ded0dd84-a3c2-456b-9274-57bad242bbc9)
![image](https://github.com/odoo-ide/vscode-odoo/assets/83392263/8a1bc784-05f7-4e1c-a2da-b6dcfc1f7756)

**Comment by trinhanhngoc** [comment]
Hello @agustin-eticco ,

Have you added the Odoo source code (https://github.com/odoo/odoo/tree/16.0) to your VSCode workspace yet?

**Comment by agustin-eticco** [comment]
Yes, i have.

![image](https://github.com/odoo-ide/vscode-odoo/assets/83392263/c454b604-06a9-4136-9ade-a8e559c7ba77)
![image](https://github.com/odoo-ide/vscode-odoo/assets/83392263/6bd2692a-6d71-4d74-80a7-f6d0f76737ca)
![image](https://github.com/odoo-ide/vscode-odoo/assets/83392263/f9c62808-c274-464c-87fb-c27ba303ea22)

**Comment by trinhanhngoc** [comment]
@agustin-eticco , I cannot reproduce the problem. Does the problem also occur with files in the Odoo source code or just with files in your custom addons?
