### ISSUE TITLE
more addons path..

### ISSUE THREAD

**Issue by LeonardoReyC** [odoo-ide/vscode-odoo#74]
After installation only base modules are detected... How can I add enterprise modules or personal modules? Thx in advance...

**Comment by trinhanhngoc** [comment]
Hello @LeonardoReyC ,

Make sure you added both the odoo source code and your custom addons to your VSCode workspace. Odoo IDE will try to recognize them automatically. If it cannot, you can manually add the Odoo source code and custom addons paths using the `python.analysis.extraPaths` setting.

<img width="1624" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/9b517094-48a3-498f-b494-adf7a0c1c88f">

**Comment by Ngquang** [comment]
@LeonardoReyC This is my setup. You can create `setting.json` in **vscode** and add `python.analysis.extraPaths`

![image](https://github.com/odoo-ide/vscode-odoo/assets/90305443/42023dff-7598-494c-8ebb-298a079303ac)

**Comment by whynotkimhari** [comment]
Hi @trinhanhngoc, though I add the path to the python.analysis.extraPaths, the Odoo IDE can't index those addons when I trigger the reindex (Cmd + Shift + P > Odoo IDE: Reindex). Any suggestions pls?

Setup: Mac + Cursor

<img width="1048" height="634" alt="Image" src="https://github.com/user-attachments/assets/c35bbf54-5c96-4324-818e-ba420316bc38" />

**Comment by trinhanhngoc** [comment]
Hello @whynotkimhari ,

Usually, you don't need to reindex manually, the Odoo IDE extension does it automatically. Depending on how many new or changed files are detected, the indexing may be fast enough that you will not see any progress indicator.

**Comment by whynotkimhari** [comment]
> Hello [@whynotkimhari](https://github.com/whynotkimhari) ,
> 
> Usually, you don't need to reindex manually, the Odoo IDE extension does it automatically. Depending on how many new or changed files are detected, the indexing may be fast enough that you will not see any progress indicator.

Thank you, however, the addons in the .venv do not get recognized/indexed. Do you have any suggestions to solve this, pls?

**Comment by trinhanhngoc** [comment]
> > Hello [@whynotkimhari](https://github.com/whynotkimhari) ,
> > Usually, you don't need to reindex manually, the Odoo IDE extension does it automatically. Depending on how many new or changed files are detected, the indexing may be fast enough that you will not see any progress indicator.
> 
> Thank you, however, the addons in the .venv do not get recognized/indexed. Do you have any suggestions to solve this, pls?

The extension currently ignores files in hidden folders. Anyway, I see that you've already added the odoo source code to your paths (`/Volumes/HP_P900/butopea/odoo/src/odoo/addons`). Why did you add another Odoo source code in the `.venv`?

**Comment by whynotkimhari** [comment]
> > > Hello [@whynotkimhari](https://github.com/whynotkimhari) ,
> > > Usually, you don't need to reindex manually, the Odoo IDE extension does it automatically. Depending on how many new or changed files are detected, the indexing may be fast enough that you will not see any progress indicator.
> > 
> > 
> > Thank you, however, the addons in the .venv do not get recognized/indexed. Do you have any suggestions to solve this, pls?
> 
> The extension currently ignores files in hidden folders. Anyway, I see that you've already added the odoo source code to your paths (`/Volumes/HP_P900/butopea/odoo/src/odoo/addons`). Why did you add another Odoo source code in the `.venv`?

My company wants to put some specific addons into the .venv folder in order to use them with uv (?, I am not sure). But in total, I can't change this company's strategy, is there a way I can overcome this? For example, symlink-ing the hidden folder, do you think this will work?

**Comment by trinhanhngoc** [comment]
@whynotkimhari ,

Yes, you can create a symlink to the addons in the `.venv` folder. It should work.

**Comment by trinhanhngoc** [comment]
Hello @whynotkimhari ,

The new version 0.45.1 has been released with support for files in `.venv`. You no longer need to create a symlink, and also no need to add a path to the `python.analysis.extraPaths` setting.

**Comment by whynotkimhari** [comment]
> Hello [@whynotkimhari](https://github.com/whynotkimhari) ,
> 
> The new version 0.45.1 has been released with support for files in `.venv`. You no longer need to create a symlink, and also no need to add a path to the `python.analysis.extraPaths` setting.

Dạ e cám ơn a nhiều nha <3
