### ISSUE TITLE
code-server support

### ISSUE THREAD

**Issue by sel-carlitos** [odoo-ide/vscode-odoo#75]
Great work!!! Great extension!!! Will you support [code-server](https://coder.com/docs/code-server/latest)? I hope you do!

**Comment by sel-carlitos** [comment]
I just saw issue #64 
But it would be much better to have support for [code-server](https://coder.com/docs/code-server/latest) as we would be installing this in Docker images built for development. It would greatly improve our developer experience.

**Comment by trinhanhngoc** [comment]
Hello @sel-carlitos,

I just published the extension to Open VSX Registry, so you can install the extension for code-server.

https://github.com/EclipseFdn/open-vsx.org/issues/2560

**Comment by sel-carlitos** [comment]
Oh my God!!!! Unbelievable!!!! Thank you very much!!!!
