### ISSUE TITLE
Doesn't support this environment (node-v119-darwin-x64)

### ISSUE THREAD

**Issue by mjavint** [odoo-ide/vscode-odoo#76]
The Odoo IDE extension doesn't support this environment (node-v119-darwin-x64)
1. Node Version - <img width="362" alt="Captura de pantalla 2024-05-15 a la(s) 7 14 23 a m" src="https://github.com/odoo-ide/vscode-odoo/assets/53498470/3a1321ff-db2d-4927-add7-7ef1f1358d55">
2. Message - <img width="531" alt="Captura de pantalla 2024-05-15 a la(s) 7 14 44 a m" src="https://github.com/odoo-ide/vscode-odoo/assets/53498470/f3d8faec-0b24-4b91-938e-54b45caa678c">

**Comment by trinhanhngoc** [comment]
Hello @mjavint ,

Thanks for the report. I just published the new version 0.27.1 to fix this issue. Please update it.

**Comment by mjavint** [comment]
Than you, excelent support
