### ISSUE TITLE
The Odoo IDE extension doesn't support this environment (node-v121-win32-x64). 

### ISSUE THREAD

**Issue by LDevlaCruzP** [odoo-ide/vscode-odoo#77]
Hello, in Windows 11 I have this problem. I have been using the extension for quite some time. The extension was working correctly until a month ago. I am using Visual Studio Code - Insiders.

![image](https://github.com/odoo-ide/vscode-odoo/assets/131502474/7a653c83-f4a2-41a5-9ef0-5477644631df)

![image](https://github.com/odoo-ide/vscode-odoo/assets/131502474/f599ef91-fce0-43ff-9ffd-68c4dec6dd1a)

**Comment by trinhanhngoc** [comment]
Hello @LDevlaCruzP ,

I just published the new version 0.27.2 with support for VSCode 1.90. You can update it now.
