### ISSUE TITLE
Support for implied fields

### ISSUE THREAD

**Issue by acgonzales** [odoo-ide/vscode-odoo#79]
Not sure if this is already supported or there's just something wrong with my config (everything else works fine 🚀) but there should be support for the implied fields such as `create_date`, `create_uid`, etc.

<img width="744" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/44025870/681c9ccc-5b18-47e1-8f14-fade25744e30">

**Comment by trinhanhngoc** [comment]
@acgonzales ,

The Odoo IDE extension already supports these implied fields. I think there are problems with your setup.

**Comment by acgonzales** [comment]
Good to know. What do you think is wrong with it? Here is how my setup goes. All other settings are default.

```
src/
├─ odoo_base/
├─ odoo_enterprise/
projects/
├─ project_a/
│  ├─ custom_module/__manifest__.py/
├─ project_b/
│  ├─ custom_module/__manifest__.py/
```

**Comment by acgonzales** [comment]
Closing it now as it has already been implemented but would like to know your input on the comment above.

**Comment by trinhanhngoc** [comment]
@acgonzales ,

How does your VSCode workspace look? Please ensure that your VSCode workspace contains all source code (Odoo source code + custom addons).
