### ISSUE TITLE
VS Code choose Odoo Version?

### ISSUE THREAD

**Issue by raphaelritter-2bit** [odoo-ide/vscode-odoo#8]
We are using your plugin for flectra (shouldn't matter except a few things) and in code-server. For me it is unclear how we can say the odoo version etc. because we are getting a lot of errors like not iteratable etc. even so it is.

What do you suggest and is there a easy way to make it completely work for flectra (in the end it is just replacing odoo with flectra keyword)? Thanks in advance for your help :)

**Comment by trinhanhngoc** [comment]
> We are using your plugin for flectra (shouldn't matter except a few things) and in code-server. For me it is unclear how we can say the odoo version etc. because we are getting a lot of errors like not iteratable etc. even so it is.
> 
> What do you suggest and is there a easy way to make it completely work for flectra (in the end it is just replacing odoo with flectra keyword)? Thanks in advance for your help :)

Anyway, can you provide screenshots of the errors you are getting?

**Comment by raphaelritter-2bit** [comment]
@trinhanhngoc thanks for the fast response and regarding flectra support i'm fully aware. As soon as i activate the extension i get a lot of messages like this:
![image](https://user-images.githubusercontent.com/126475713/228425508-77fc8a2d-9007-425e-9f5d-40e1eaf3c90f.png)
Even in OCA modules etc. I think it is not detecting the proper odoo version which lies below (odoo14 / Flectra 2) or am I seeing this wrong?

**Comment by trinhanhngoc** [comment]
@raphaelritter-2bit Looks like you are facing the same problem in #7 . I guess your workspace structure is the cause. Can you share with me your workspace structure so I can reproduce the error myself?

**Comment by raphaelritter-2bit** [comment]
@trinhanhngoc well we start everything from our git repo, meaning flectra resources can't be found there only our addons. Does that mean the plugin only works with we would copy our addons into addons folder of flectra code and open code-server on that level?

**Comment by trinhanhngoc** [comment]
@raphaelritter-2bit No, you don't need to copy anything. But you need to tell VSCode about the location of flectra source code. Otherwise, VSCode can not resolve the class `flectra.models.BaseModel` and you will get errors like you said.

You can follow this guide to add the flectra source code as another workspace root besides your addons:  https://github.com/odoo-ide/vscode-odoo/issues/7#issuecomment-1455401738. 

Also see: [VSCode multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces)
