### ISSUE TITLE
Is there a way to install the extension on an arm based system ?

### ISSUE THREAD

**Issue by PeteKraft** [odoo-ide/vscode-odoo#80]
When trying to install the extension in VSCode, I am receiving the following error:

`The Odoo IDE extension doesn't support this environment (node-v121-linux-arm64). Please request support at [https://github.com/odoo-ide/vscode-odoo/issues](https://github.com/odoo-ide/vscode-odoo/issues).`

Is there anything I can do to circumvent the error ?

**Comment by trinhanhngoc** [comment]
Hello @PeteKraft,

The extension depends on native node modules, so some node environments such as electron arm are not currently supported yet. As a workaround, you can setup a container and use the [VS Code Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) feature to install the extension.

**Comment by PeteKraft** [comment]
ooh... that's uncharted territory for me, I'll have to check it out.
Thanks for the pointer.
