### ISSUE TITLE
Vscode is invalid in XML reference field

### ISSUE THREAD

**Issue by yao-big** [odoo-ide/vscode-odoo#82]
I seem to have found a bug. This plugin imports into Odoo correctly on the backend. For example, when I use <field name="m" />, according to the operation guide, fields starting with "m" should appear, but they do not. Adding a group to the field also does not make it appear. Importing it in JavaScript also fails. My operating system is Mac M2, and the Odoo version I am using is Odoo 16.

**Comment by yao-big** [comment]
I noticed that it seems to only work for Python files, and not for other files. How should I configure this? Could it be because my operating system is ARM?

**Comment by trinhanhngoc** [comment]
@yao-big , 

Can you provide screenshots of the problem?

**Comment by yao-big** [comment]
OK的 ,
![image](https://github.com/odoo-ide/vscode-odoo/assets/30170943/0d9b722b-b300-449e-8b13-4812c5e86dde)
There is no prompt here

There is no prompt here
Because I think the introduction is acceptable

**Comment by yao-big** [comment]
![image](https://github.com/odoo-ide/vscode-odoo/assets/30170943/7614d17c-c293-4a25-a42c-e55fee043c3c)
 
This is your introduction 
It looks like it's possible

**Comment by trinhanhngoc** [comment]
@yao-big ,

Do you mean code completion does not work when typing field names?

**Comment by yao-big** [comment]
yes

**Comment by trinhanhngoc** [comment]
@yao-big , 

Have you tried manually triggering code completion by `Control + Space`? Does it work?

**Comment by yao-big** [comment]
Just tried using shortcut keys, but it's okay. Can't it come out automatically?

**Comment by yao-big** [comment]
"I just tried using the shortcut keys, and it works. Can't it come up automatically?"

**Comment by trinhanhngoc** [comment]
@yao-big ,

To trigger code completion automatically when typing in strings, you need to tweak `editor.quickSuggestions` setting.

<img width="882" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/10ffec6d-ee96-4747-b0e1-5efdabf0eed6">

**Comment by yao-big** [comment]
Okay, that's it. Thank you very much

**Comment by yao-big** [comment]
I have noticed that recently this plugin has been using a lot of CPU resources. This should be a bug, right?
@trinhanhngoc

**Comment by yao-big** [comment]
<img width="1800" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/30170943/4e338816-26c5-4f8b-8978-59f14061563e">

**Comment by trinhanhngoc** [comment]
@yao-big ,

Look at your screenshot, I don't see any CPU consumption issues. CPU% value is zero.

**Comment by yao-big** [comment]
No, he sometimes takes up a lot of CPU

**Comment by trinhanhngoc** [comment]
@yao-big ,

I tested with large files (eg `account/models/account_move.py`) and don't see any CPU performance issues on Macbook Pro M1. CPU usage is only high in about 1 second after editing files because the extension needs to re-analysis files.

**Comment by yao-big** [comment]
When will this problem be solved? Release new version updates?

**Comment by yao-big** [comment]
@trinhanhngoc

**Comment by trinhanhngoc** [comment]
> @yao-big ,
> 
> I tested with large files (eg `account/models/account_move.py`) and don't see any CPU performance issues on Macbook Pro M1. CPU usage is only high in about 1 second after editing files because the extension needs to re-analyse files.

@yao-big ,

As I said, I consider this behaviour to be normal. So there is no fix.
