### ISSUE TITLE
Redirection to the wrong odoo folder

### ISSUE THREAD

**Issue by cimbaIG** [odoo-ide/vscode-odoo#85]
I have a problem.

I have directory odoo/ containing two subdirectories (odoo/odoo16 and odoo/odoo17). I created two workspaces, one for odoo 16 and another one for odoo 17. The Python virtual environment is properly loaded for both Odoo versions. However, in Odoo 17 workspace imports are from odoo 16 folder. Why?

For instance:
from odoo.http import request

When I press CTRL and click on odoo, it redirects me to the odoo 16 folder __init_.py file (not the odoo 17 folder!). What is going on?

Thank you.

**Comment by trinhanhngoc** [comment]
Hello @cimbaIG ,


How do you structure your project in VSCode? It's better if you can provide screenshots.

**Comment by cimbaIG** [comment]
Hi @trinhanhngoc !

I just realized where was the issue. It does not have anything with your extension. The problem appeared because wrong settings file was read by the Default profile. I deleted this default settings.json file and created my own. After that everything worked fine. :)
