### ISSUE TITLE
Odoo information not loaded in XML

### ISSUE THREAD

**Issue by Sylvain-Caron** [odoo-ide/vscode-odoo#87]
Since installing the extension on my new PC, the extension no longer detects the odoo information, I had to put that
![image](https://github.com/user-attachments/assets/137d7d4b-2451-4243-b461-94c860da8269) in the settings.json for the ptyhon and it works, but nothing for the xml 

Any idea?

![image](https://github.com/user-attachments/assets/1151f507-2083-41b1-9cf1-4de8e4d1951c)

**Comment by trinhanhngoc** [comment]
Hello @Sylvain-Caron ,

Have you added the odoo source code folder to VSCode? The same problem: https://github.com/odoo-ide/vscode-odoo/issues/81#issuecomment-2367446620.

**Comment by Sylvain-Caron** [comment]
It works by putting odoo and odoo enterprise at the root. while I have a ".versions" folder in which I would like to put and make the path in the settings file, thanks for the link I will look at that
