### ISSUE TITLE
Reload fails when using module to start odoo

### ISSUE THREAD

**Issue by 8191** [odoo-ide/vscode-odoo#88]
I typically run Odoo with the `--dev reload` flag. Unfortunately this fails, when I start Odoo via the module, with following error:
```Python traceback
Traceback (most recent call last):
  File "/Users/mf/Source/odoo/odoo-17.0+e.20240626/odoo/__main__.py", line 1, in <module>
    from .cli.command import main
ImportError: attempted relative import with no known parent package
```

My launch config looks like this:
```json
"name": "Odoo 17 with Debug",
"type": "debugpy",
"request": "launch",
"module": "odoo",
"cwd": "${workspaceFolder:odoo}",
"args": [
	"--dev",
	"reload,xml",
	"--database",
	"hola2",
	"--update",
	"${input:moduleName}"
]
```

### Workaround
I use a small script to start Odoo:
```python
import odoo
odoo.cli.main()
```

I've changed the `"module": "odoo"` part in the launch config to `"program": "odoo.py"`.

**Comment by trinhanhngoc** [comment]
Hello @8191 ,

I just tested and could not reproduce your problem.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/012bf109-2b13-454d-8c85-9e79c9f6e681">

Anyway, I don't think the Odoo IDE extension is causing your problem.

**Comment by 8191** [comment]
@trinhanhngoc Thanks for your fast response!
You are right, that issue is not related to Odoo IDE. I thought the `module` parameter in the launch configuration refers to the VSCode module "odoo", but in fact it refers to a Python module... 😊  Sorry for any confusion.

Maybe the issue does not occur for you as you do not have the watchdog module installed, which monitors Python files in the odoo directory for modification.
